In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout

Using TensorFlow backend.


There are multiple ways of loading data depending on where you load it from. Just run the relevant code block below (or add your own)

Note: I am not sure about  order of psi and phi. 
index => 0,1,2,3,...
pdb => unique name of protein
pdb_aa => amino acid sequence over 21 chars
q8 => sequence over eight chars
dist_matrix =>  ouput 1

FOR PART II
outputs are psi and phi

In [4]:
def load_pickle(datafile):
    # load train data for a specific fold
    with open(datafile, 'rb') as f:
        data =  pickle.load(f)
    return data

In [114]:
indices, pdbs, length_aas, pdb_aas, q8s, dcalphas, psis, phis, msas = load_pickle("../data/train_fold_3.pkl")

In [56]:
#get the max length of some input sequence
max_length = max(length_aas)

Data Preprocessing

In [10]:
from keras.preprocessing import sequence

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [103]:
aa_list = list('ACEDGFIHKMLNQPSRTWVYX') + ['NoSeq'] #CHECK THIS
q8_list      = list('LBEGIHST') + ['NoSeq']

In [104]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import text_to_word_sequence

In [109]:
from keras.utils import to_categorical

In [184]:
vocab_size = len(aa_list)

In [185]:
text = " ".join(list(pdb_aas[2]))

In [186]:
result = one_hot(text, round(vocab_size))

In [187]:
result = np.array(result)

In [188]:
result

array([ 9,  3,  3, 16, 12, 11, 12, 16, 16,  5, 16, 11,  9, 16, 11, 11, 13,
        3, 11,  3, 13, 20, 15,  3, 16, 16, 15, 16, 16,  6, 15, 12, 12, 11,
       11,  3,  9, 13, 11, 15, 16, 12, 18, 16, 16, 12, 12,  3,  3, 16,  3,
       11,  3,  5,  9,  3, 16,  6, 11,  5,  9,  6,  3,  9,  3, 20,  9, 20,
        3, 13, 13, 11, 12,  3,  3, 11, 15,  3, 13, 15,  5,  5, 13, 16, 16,
        6, 15,  9, 20, 13,  3,  3, 18,  6,  9,  5,  3, 19,  5,  9, 16,  5,
       15,  5,  6,  3, 12,  9])

In [189]:
encoded = to_categorical(result)

In [190]:
encoded = encoded.T

In [191]:
encoded.shape

(21, 108)

In [192]:
encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [193]:
max_length = 120

In [194]:
#pad the sequence
input_train = sequence.pad_sequences(encoded, maxlen=max_length, padding = "post")

In [195]:
input_train.shape

(21, 120)

In [196]:
#example => this is 9. padding adds only zero vectors
input_train[:,0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

In [91]:
#preprocess the whole file?

In [ ]:
#copying code from https://danijar.com/variable-sequence-lengths-in-tensorflow/

In [197]:
input_train = input_train.T

In [198]:
input_train = np.expand_dims(input_train, axis=0)

In [199]:
#dimensions of data => batch size x max length x features
input_train.shape

(1, 120, 21)

In [209]:
def length(data):
    sequence = tf.convert_to_tensor(data, dtype=tf.float32)
    used = tf.sign(tf.reduce_max(tf.abs(sequence), 2))
    length = tf.reduce_sum(used, 1)
    length = tf.cast(length, tf.int32)
    return length

In [213]:
r = length(input_train)

In [ ]:
#this function would return a vector with the length of every single element in the batch 

In [214]:
with tf.Session() as sess:
    # This tells Tensorflow we woud like to evaluate the Tensor `result`. 
    output = sess.run(r)
    print(output)

[108]


In [17]:
def produce_test_output(testfile, save_path):
    test_input = pd.read_csv(testfile, header=None)
    protein_names = np.array(test_input.iloc[:,1])
    protein_len = np.array(test_input.iloc[:,2])

    # concatenate all output to one-dimensional
    all_data = []
    all_names = []
    for i, pname in enumerate(protein_names):
        dist_flat = dist[i].ravel()
        array = np.concatenate([dist_flat, psi[i], phi[i]])
        all_data.append(array)

        length = protein_len[i]
        dist_names = ["{}_d_{}_{}".format(pname, i + 1, j + 1) for i in range(length) for
                j in range(length)]

        psi_names = ["{}_psi_{}".format(pname, i + 1) for i in range(length)]
        phi_names = ["{}_phi_{}".format(pname, i + 1) for i in range(length)]
        row_names = np.array(dist_names + psi_names + phi_names)
        all_names.append(row_names)

    all_data = np.concatenate(all_data)
    all_names = np.concatenate(all_names)
    output = {"Id": all_names, "Predicted": all_data}
    output = pd.DataFrame(output)
    output.to_csv(save_path, index=False)

In [207]:
import numpy as np

def my_func(arg):
    arg = tf.convert_to_tensor(arg, dtype=tf.float32)
    return tf.matmul(arg, arg) + arg

# The following calls are equivalent.
value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))

In [208]:
value_1

<tf.Tensor 'add:0' shape=(2, 2) dtype=float32>